main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('appointment/', include('appointment.urls')),
    path('sign/', include('sign.urls')),
    # path('accounts/', include('allauth.urls')),
]

main/news/urls.py
from django.urls import path, include
from .views import NewsListView, NewsDetailView, NewsCreateView, NewsDeleteView, NewsUpdateView, View
from . import views
from django.views.decorators.cache import cache_page


app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name='news_list'),
    path('<int:pk>/detail', NewsDetailView.as_view(), name='news_detail'),
    path('create/', NewsCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),
    path('<int:pk>/update/', NewsUpdateView.as_view(), name='news_update'),
    path('noview/', View.as_view(), name='set_language'),
]

main/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from django.views.decorators.cache import cache_page


app_name = 'sign'


urlpatterns = [
    path('login/',
         cache_page(60*10)(LoginView.as_view(template_name='sign/login.html')),
         name='login'),
    path('logout/',
         cache_page(60*10)(LogoutView.as_view(template_name='sign/logout.html')),
         name='logout'),
    path('signup/',
         cache_page(60*10)(BaseRegisterView.as_view(template_name='sign/signup.html')),
         name='signup'),
]

main/news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.core.cache import cache
from django.urls import reverse
from datetime import datetime
from django.core.cache import cache


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)

    def update_rating(self):
        total_post_rating = sum(post.rating * 3 for post in self.posts.all())
        total_comment_rating = sum(comment.rating for comment in self.comments.all())
        total_post_comment_rating = sum(comment.rating for post in self.posts.all() for comment in post.comments.all())
        self.rating = total_post_rating + total_comment_rating + total_post_comment_rating
        self.save()

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('mails:news_detail', args=[str(self.id)])


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    POST_TYPES = [
        ('article', 'Article'),
        ('news', 'News'),
    ]
    post_type = models.CharField(max_length=10, choices=POST_TYPES)
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)

    def update_rating(self):
        total_comments_rating = sum(comment.rating for comment in self.comments.all())
        self.rating = total_comments_rating
        self.save()

    def __str__(self):
        return self.title


class PostCategory(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f"Comment by {self.user.username} on {self.post.title}"

















main/news/news/forms.py
from django.forms import ModelForm, TextInput, Textarea
from .models import Post, Comment
from django.core.exceptions import ValidationError


class NewsForm(ModelForm):

    class Meta:
        model = Post
        fields = [
            'author',
            'title',
            'text',
            'post_type',
            'rating',

        ]
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название'
            }),
            'content': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание'
            }),
        }

    def clean(self):
        cleaned_data = super().clean()
        author = cleaned_data.get('author')
        title = cleaned_data.get('title')
        text = cleaned_data.get('text')

        # if author[0].islower():
        #     raise ValidationError(
        #         "Имя Автора должно начинаться с заглавной буквы"
        #     )
        if title == author:
            raise ValidationError(
                "Заголовок не может быть идентичным названию Автора"
            )
        elif len(text) < 20:
            raise ValidationError(
                "Описание новости не может быть таким коротким"
            )

        return cleaned_data




main/news/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, DetailView, CreateView, DeleteView, UpdateView, TemplateView
from django.urls import reverse_lazy
from django.core.cache import cache  # Импортируем наш кэш
from django.contrib.auth.mixins import LoginRequiredMixin

from .filters import NewsFilter
from .forms import NewsForm
from .models import Post
from django.http.response import HttpResponse  # импортируем респонс для проверки текста
from django.utils.translation import gettext as _  # импортируем функцию для перевода
from django.utils.translation import activate, get_supported_language_variant
from main.settings import LANGUAGE_SESSION_KEY
import pytz  #  импортируем стандартный модуль для работы с часовыми поясами
from django.utils import timezone
# Create your views here.


class NewsListView(ListView):
    model = Post
    template_name = 'news_list.html'
    context_object_name = 'news'
    ordering = '-id'
    paginate_by = 4

    # Функция для фильтра
    def get_queryset(self):
        # Получаем обычный запрос
        queryset = super().get_queryset()
        # Используем наш класс фильтрации.
        # self.request.GET содержит обьект QueryDict
        # Сохраняем нашу фильтрацию в объекте класса,
        # чтобы потом добавить в контекст и использовать в шаблоне.
        self.filterset = NewsFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список товаров
        return self.filterset.qs

    # Вывод даты и времени
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class NewsDetailView(DetailView):
    template_name = 'news_detail.html'
    context_object_name = 'new'
    queryset = Post.objects.all()

    def get_object(self, *args, **kwargs): # переопределяем метод получения объекта, как ни странно
        obj = cache.get(f'title-{self.kwargs["pk"]}', None) # кэш очень похож на словарь, и метод get действует так же. Он забирает значение по ключу, если его нет, то забирает None.

         # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'title-{self.kwargs["pk"]}', obj)

        return obj


    """ '''
        И вроде бы всё готово. Если объекта нет в кэше, то мы берём его из БД и кэшируем, а если есть, то сразу берём из кэша и возвращаем. Но! Давайте узнаем, что же будет происходить сейчас (не забудьте убрать кэширование из urls.py, иначе получится очень грязно!).

        Зайдите на кэшируемую страницу и попробуйте через админ-панель что-либо в ней поменять, а потом обновите страницу.

        И тут-то вас ждёт сюрприз! Весь нюанс в том, что теперь ничего не поменяется вообще… Никогда... Ведь мы не установили реакцию на редактирование объекта. Когда объект меняется его надо удалять из кэша, чтобы ключ сбрасывался и больше не находился.

        Давайте этим и займёмся, переопределим метод save в sample_app/models.py.

        from django.core.cache import cache
        
        
        class Product(models.Model):
            name = models.CharField(max_length=200)
            price = models.FloatField(validators=[MinValueValidator(0.0, 'Price should be >= 0.0')])
            quantity = models.IntegerField(validators=[MinValueValidator(0, 'Quantity should be >= 0')])
            category = models.ForeignKey('Category', on_delete=models.CASCADE)
        
            def __str__(self):
                return f'{self.name} {self.quantity}'
        
            def get_absolute_url(self): # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
                return f'/products/{self.id}'
        
            def save(self, *args, **kwargs):
                super().save(*args, **kwargs) # сначала вызываем метод родителя, чтобы объект сохранился
                cache.delete(f'product-{self.pk}') # затем удаляем его из кэша, чтобы сбросить его
        '''
"""


class NewsCreateView(CreateView):
    form_class = NewsForm
    model = Post
    template_name = 'news_create.html'
    success_url = reverse_lazy('news:news_list')


class NewsUpdateView(UpdateView):
    form_class = NewsForm
    model = Post
    template_name = 'news_update.html'
    success_url = reverse_lazy('news:news_list')


class NewsDeleteView(DeleteView):
    model = Post
    template_name = 'news_delete.html'
    success_url = reverse_lazy('news:news_list')


class Index(View):
    def get(self, request):
        curent_time = timezone.now()

        # .  Translators: This message appears on the home page only
        models = Post.objects.all()

        context = {
            'models': models,
            'current_time': timezone.now(),
            'timezones': pytz.common_timezones  # добавляем в контекст все доступные часовые пояса
        }

        return HttpResponse(render(request, 'index.html', context))


    #  по пост-запросу будем добавлять в сессию часовой пояс, который и будет обрабатываться написанным нами ранее middleware
    def post(self, request):
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/')

main/news/templates/index.html
{% load i18n %}
{% load tz %} <!-- не забываем загрузить тег для работы с часовыми поясами -->

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page title</title>
</head>
<body>

    <form method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">

        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %} >
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>

    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>

    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->

    {% for model in models %}
    <div class="model-class">
        {{ model.name }}
    </div>
    {% endfor %}
</body>
</html>

main/news/templates/news_detail.html
{% extends 'news/main.html' %}
{% load custom_filters %}

{% block content %}
<br>
<br>
<br>
<br>
    <h1>News Detail</h1>
<div class="alert alert-warning mt=2">
    <h1>Author: {{ new.author }}</h1>
    <h2>Title: {{ new.title }}</h2>
    <p>Дата: {{ new.created_at }}</p>
    <p>{{ new.text }}</p>
    <p>rating: {{ new.rating }}</p>
            <div class="container">
                    <div class="text-center mt-10">
                        <a href="update/">Редактировать Задачу</a>
                        <a href="delete/">Удалить Задачу</a>
                    </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
    </div>
</div>
{% endblock %}


main/news/templates/news_list.html
{% extends 'news/main.html' %}
{% load i18n %}
{% load custom_filters %}

{% block title %} Главная {% endblock %}

{% block content %}
<br>
<br>
<br>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page title</title>
</head>
<body>
    <form method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST-запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">

        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %} >
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>

    {% for model in models %}
    <div class="model-class">
        {{ model.name }}
    </div>
    {% endfor %}
</body>
</html>
<br>
<br>
<br>
        <div class="container">
        <h1>Табель Новостей</h1>
        <br>
            <form action="" method="GET">
                {{ filterset.form.as_p }}
                <input type="submit" value="Поиск">
            </form>
            <br>
                {% for new in news %}
                    <div class="alert alert-warning mt-1">
                        <a href="{% url 'news:news_detail' new.id %}"><h3>Author: {{ new.author }}</h3></a>
                        <p>Title :{{ new.title|truncatewords:2 }}</p>
                    </div>
                {% empty %}
                    <p>Табель Новостей Пуст</p>
                {% endfor %}

        </div>
<!--<button> <a href="sign/logout/">Выйти</a> </button>-->

{# Добавляем пагинацию на страницу #}

    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

<br>
<br>
<br>
<form action="{% url 'sign:logout' %}" method="post">
    {% csrf_token %}
</form>
<a href="{% url 'news:set_language' %}">view</a>
{% endblock %}