main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('appointment/', include('appointment.urls')),
    path('sign/', include('sign.urls')),
    # path('accounts/', include('allauth.urls')),
]

main/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from django.views.decorators.cache import cache_page


app_name = 'sign'


urlpatterns = [
    path('login/',
         cache_page(60*10)(LoginView.as_view(template_name='sign/login.html')),
         name='login'),
    path('logout/',
         cache_page(60*10)(LogoutView.as_view(template_name='sign/logout.html')),
         name='logout'),
    path('signup/',
         cache_page(60*10)(BaseRegisterView.as_view(template_name='sign/signup.html')),
         name='signup'),
]

main/sign/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class BaseRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )


# Создаем форму, который добавляет пользователей в базовую группу, при успешной авторизаций
class BasicSignupForm(SignupForm):

    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        # basic_group = Group.objects.get(name='basic')
        # basic_group.user_set.add(user)
        return user

main/sign/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .models import BaseRegisterForm

from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required


class BaseRegisterView(CreateView):
    model = User
    form_class = BaseRegisterForm
    success_url = reverse_lazy('sign:login')



main/sign/templates/sign/login.html
{% extends "main.html" %}

{% block content %}
<div class="container">
            <div class="text-center mt-10">
<h2> Войти в систему </h2>
<form method="post" action="{% url 'sign:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Войти">
</form>
<button> <a href="{% url 'sign:signup' %}"> Регистрация </a></button>
                </div>
        </div>
{% endblock content %}

main/sign/templates/sign/logout.html
{% extends "main.html" %}

{% block content %}


{% endblock %}

main/sign/templates/sign/signup.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registration</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
</body>
</html>


