news/urls.py
from django.urls import path, include
from .views import NewsListView, NewsDetailView, NewsCreateView, NewsDeleteView, NewsUpdateView, PostListView, \
    PostDetailView
from . import views
from django.views.decorators.cache import cache_page


app_name = 'news'

urlpatterns = [
    path('news/', PostListView.as_view(), name='news_ser'),
    path('new/<int:id>/', PostDetailView.as_view(), name='post_detail'),
    path('', NewsListView.as_view(), name='news_list'),
    path('<int:pk>/detail', NewsDetailView.as_view(), name='news_detail'),
    path('create/', NewsCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),
    path('<int:pk>/update/', NewsUpdateView.as_view(), name='news_update'),
    # path('noview/', IndexTime.as_view(), name='set_time'),
    # path('translateView/', IndexLanguage.as_view(), name='set_language'),
]

news/templates/about.html
{% extends 'news/main.html' %}

{% block title %} Страница про нас {% endblock %}

{% block content %}
<br>
<br>
<br>
<br>
    <h4>
        Этот Сайт был предназначен для новостей
    </h4>
        <h1><a href="{% url 'appointment:make_appointment' %}">Озодекка сообщуния жонатким кевотти</a></h1>
{% endblock %}

news/templates/index.html
{% load i18n %}
{% load tz %} <!-- не забываем загрузить тег для работы с часовыми поясами -->


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page title</title>
    <!-- Если сейчас больше чем 19 или же меньше 7, то выводим тёмную тему, иначе выводим светлую -->
    <style>
        body {background-color: {% if current_time.hour >= 19 or current_time.hour <= 7 %} darkcyan {% else %} powderblue {% endif %};}
    </style>
</head>
<body>

    <form action="{% url 'news:set_time' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST-запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">

        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected >{% endif %} >
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>

    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>

    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->

    {% for new in news %}
    <div class="model-class">
        {{ new.name }}
    </div>
    {% endfor %}


</body>
</html>

news/templates/news_create.html
{% extends 'news/main.html' %}


{% block content %}
<br>
<br>
<br>
    <h1>Создать Новость</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success">Добавить</button>
    </form>
{% endblock %}


news/templates/news_delete.html
{% extends 'news/main.html' %}


{% block content %}
<br>
<br>
<br>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <h1>Удалить Новость {{ object.title }}</a></h1>

        <button type="submit" class="btn btn-success">Delete</button>
    </form>
{% endblock %}

news/templates/news_detail.html
{% extends 'news/main.html' %}
{% load custom_filters %}

{% block content %}
<br>
<br>
<br>
<br>
    <h1>News Detail</h1>
<div class="alert alert-warning mt=2">
    <h1>Author: {{ new.author }}</h1>
    <h2>Title: {{ new.title }}</h2>
    <p>Дата: {{ new.created_at }}</p>
    <p>{{ new.text }}</p>
    <p>rating: {{ new.rating }}</p>
            <div class="container">
                    <div class="text-center mt-10">
                        <br>
                        <a href="update/">Редактировать Задачу</a>
                        <br>
                        <a href="delete/">Удалить Задачу</a>
                        <br>
                        <a href="{% url 'news:post_detail' new.id %}">restApi</a>
                    </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
    </div>
</div>
{% endblock %}


news/templates/news_list.html
{% extends 'news/main.html' %}
{% load i18n %}
{% load custom_filters %}

{% block title %} Главная {% endblock %}

{% block content %}
<br>
<br>
<br>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page title</title>
</head>
<body>
    {% comment %}
    <form method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST-запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">

        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %} >
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>
    {% endcomment %}

    {% for model in models %}
    <div class="model-class">
        {{ model.name }}
    </div>
    {% endfor %}
</body>
</html>

        <div class="container">
        <h1>Табель Новостей</h1>
        <br>
            <form action="" method="GET">
                {{ filterset.form.as_p }}
                <input type="submit" value="Поиск">
            </form>
            <br>
                {% for new in news %}
                    <div class="alert alert-warning mt-1">
                        <a href="{% url 'news:news_detail' new.id %}"><h3>Author: {{ new.author }}</h3></a>
                        <p>Title :{{ new.title|truncatewords:2 }}</p>
                    </div>
                {% empty %}
                    <p>Табель Новостей Пуст</p>
                {% endfor %}

        </div>
<!--<button> <a href="sign/logout/">Выйти</a> </button>-->

{# Добавляем пагинацию на страницу #}

    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

<br>
<br>
<br>
<form action="{% url 'sign:logout' %}" method="post">
    {% csrf_token %}
</form>


{% comment %}
<br>
<br>
<a href="{% url 'news:set_time' %}">timezone</a>
<br>
<br>
<a href="{% url 'news:set_language' %}">language</a>
{% endcomment %}
<a href="{% url 'news:news_ser' %}">restApi</a>
{% endblock %}

news/templates/news_update.html
{% extends 'news/main.html' %}


{% block content %}
<br>
<br>
<br>
    <h1>Редактировать Новость</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success">Редактировать</button>
    </form>
{% endblock %}


news/templates/swagger-ui.html
<!DOCTYPE html>
<html>
 <head>
   <title>Swagger</title>
   <meta
charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
 </head>
 <body>
   <div id="swagger-ui"></div>
   <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
   <script>
   const ui = SwaggerUIBundle({
       url: "//static/openapi-schema.yml",
       dom_id: '#swagger-ui',
       presets: [
         SwaggerUIBundle.presets.apis,
         SwaggerUIBundle.SwaggerUIStandalonePreset
       ],
       layout: "BaseLayout",
       requestInterceptor: (request) => {
         request.headers['X-CSRFToken'] = "{{ csrf_token }}"
         return request;
       }
     })
   </script>
 </body>
</html>